Traceback (most recent call last):
  File "/Users/casp/miniconda3/envs/missionbio.mosaic/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/casp/miniconda3/envs/missionbio.mosaic/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/casp/miniconda3/envs/missionbio.mosaic/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/casp/miniconda3/envs/missionbio.mosaic/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/casp/miniconda3/envs/missionbio.mosaic/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/casp/miniconda3/envs/missionbio.mosaic/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/casp/miniconda3/envs/missionbio.mosaic/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/casp/miniconda3/envs/missionbio.mosaic/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

read_counts= sample.protein.layers["read_counts"]
ids = sample.protein.col_attrs["id"].copy()
raw = pd.DataFrame(read_counts, columns=ids)

total_ab = pd.DataFrame(raw.sum(axis = 0, skipna = True))
total_ab.columns =['Raw Count']
total_ab.index.name = 'Antibody'
total_ab.reset_index(inplace=True)
total_ab['percent'] = (total_ab['Raw Count'] / total_ab['Raw Count'].sum()) * 100
print(total_ab)

#Pie chart
#fig = px.pie(total_ab, values='Raw Count',names='Antibody', title='Sum of Raw')

#Bar chart
fig = px.bar(total_ab, x='Antibody', y='percent')
fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [21][0m, in [0;36m<cell line: 18>[0;34m()[0m
[1;32m     12[0m [38;5;28mprint[39m(total_ab)
[1;32m     14[0m [38;5;66;03m#Pie chart[39;00m
[1;32m     15[0m [38;5;66;03m#fig = px.pie(total_ab, values='Raw Count',names='Antibody', title='Sum of Raw')[39;00m
[1;32m     16[0m 
[1;32m     17[0m [38;5;66;03m#Bar chart[39;00m
[0;32m---> 18[0m fig [38;5;241m=[39m [43mpx[49m[38;5;241m.[39mbar(total_ab, x[38;5;241m=[39m[38;5;124m'[39m[38;5;124mAntibody[39m[38;5;124m'[39m, y[38;5;241m=[39m[38;5;124m'[39m[38;5;124mpercent[39m[38;5;124m'[39m)
[1;32m     19[0m fig[38;5;241m.[39mshow()

[0;31mNameError[0m: name 'px' is not defined
NameError: name 'px' is not defined

